intro:
title: 'Neural Additive Models: Interpretable Machine Learning with Neural Nets'
description:
- ICML 2020 Workshop on Human Interpretability in Machine Learning (Spotlight)
buttons:
  Paper: 'https://arxiv.org/pdf/2004.13912.pdf'
  Code: 'https://github.com/google-research/google-research/tree/master/neural_additive_models'
  TweetPrint: https://twitter.com/nickfrosst/status/1255889440083447810?s=20
  Authors: '#authors'
